# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='编号')),
                ('size', models.CharField(blank=True, max_length=128, null=True, verbose_name='容量')),
                ('room_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='机房编号')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '机柜',
                'verbose_name_plural': '机柜',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='厂商')),
                ('model', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='型号')),
                ('types', models.SmallIntegerField(choices=[(0, '服务器'), (1, 'CPU'), (2, '硬盘'), (3, '内存'), (4, '网络设备')], default=0, verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '厂商',
                'verbose_name_plural': '厂商',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernel', models.IntegerField(verbose_name='核数')),
                ('frequency', models.CharField(blank=True, max_length=12, null=True, verbose_name='主频')),
                ('counts', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('name', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdbServer.Company', verbose_name='厂商')),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPU',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.SmallIntegerField(choices=[(0, '交换机'), (1, '路由器'), (2, '防火墙'), (3, 'IDS/IPS'), (4, 'WAF'), (5, 'DDOS防火墙')], default=0, verbose_name='设备类型')),
                ('ipaddress', models.GenericIPAddressField(unique=True)),
                ('height', models.CharField(blank=True, max_length=4, null=True, verbose_name='高度')),
                ('position', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='机柜位置')),
                ('device_statuses', models.SmallIntegerField(choices=[(0, '未启用'), (1, '已启用'), (2, '故障'), (3, '下线')], default=0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('cabint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='cmdbServer.Cabint')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdbServer.Company')),
            ],
            options={
                'verbose_name': '网络设备',
                'verbose_name_plural': '网络设备',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('types', models.SmallIntegerField(blank=True, choices=[(0, 'SATA硬盘'), (1, 'SCSI硬盘'), (2, 'SAS硬盘'), (3, 'SSD硬盘')], default=0, null=True, verbose_name='磁盘类型')),
                ('size', models.CharField(max_length=32, verbose_name='磁盘容量')),
                ('name', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdbServer.Company', verbose_name='厂商')),
            ],
            options={
                'verbose_name': '磁盘',
                'verbose_name_plural': '磁盘',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='机房名称')),
                ('address', models.CharField(max_length=200, verbose_name='机房地址')),
                ('contacts', models.CharField(blank=True, max_length=32, null=True, verbose_name='机房联系组')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='联系电话')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '机房信息',
                'verbose_name_plural': '机房信息',
            },
        ),
        migrations.CreateModel(
            name='Nic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP地址')),
                ('speed', models.SmallIntegerField(choices=[(0, '万兆'), (1, '千兆'), (2, '百兆')], default=2, verbose_name='速率')),
                ('types', models.SmallIntegerField(choices=[(0, '服务器')], default=0, verbose_name='类型')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('name', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdbServer.Company', verbose_name='厂商')),
            ],
            options={
                'verbose_name': '网卡',
                'verbose_name_plural': '网卡',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(choices=[(0, 'VLAN'), (1, 'TRUNK'), (2, 'RIP'), (3, 'OSPF'), (4, 'IBGP'), (5, 'EBGP')], default=0, verbose_name='协议类型')),
                ('number', models.CharField(default='VLAN1', max_length=8, verbose_name='协议号')),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='协议IP')),
                ('port_range', models.CharField(default='1-4', max_length=8, verbose_name='端口范围')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='cmdbServer.Devices')),
            ],
            options={
                'verbose_name': '协议',
                'verbose_name_plural': '协议',
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('size', models.CharField(default='32G', max_length=32, verbose_name='运行内存')),
                ('count', models.IntegerField(default='1', verbose_name='数量')),
                ('name', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdbServer.Company', verbose_name='厂商')),
            ],
            options={
                'verbose_name': '内存',
                'verbose_name_plural': '内存',
            },
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('types', models.SmallIntegerField(blank=True, choices=[(0, '机架'), (1, '塔式'), (2, '小型机'), (3, '刀片')], null=True, verbose_name='服务器类型')),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='主机名')),
                ('ipmi_ipaddress', models.GenericIPAddressField(unique=True, verbose_name='管理IP')),
                ('system', models.CharField(blank=True, max_length=32, null=True, verbose_name='操作系统')),
                ('version', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统版本号')),
                ('height', models.CharField(blank=True, max_length=4, null=True, verbose_name='高度')),
                ('position', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='机柜位置')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('device_statuses', models.SmallIntegerField(choices=[(0, '未启用'), (1, '已启用'), (2, '故障'), (3, '下线')], default=0)),
                ('cabint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='cmdbServer.Cabint')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='cmdbServer.Company')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='cmdbServer.Protocol', verbose_name='交换机')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
            },
        ),
        migrations.AddField(
            model_name='ram',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rams', to='cmdbServer.Servers'),
        ),
        migrations.AddField(
            model_name='nic',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nics', to='cmdbServer.Servers'),
        ),
        migrations.AddField(
            model_name='disk',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='cmdbServer.Servers'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpus', to='cmdbServer.Servers'),
        ),
        migrations.AddField(
            model_name='cabint',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabintd', to='cmdbServer.IDC'),
        ),
    ]
