# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-26 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitors',
            name='host',
        ),
        migrations.DeleteModel(
            name='Monitors',
        ),
    ]
