# Generated by Django 2.1.3 on 2018-12-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonding',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
    ]
