# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-11 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='certif',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='证书'),
        ),
    ]
