# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servers',
            name='protocol',
        ),
        migrations.AddField(
            model_name='nic',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nics', to='cmdbServer.Protocol', verbose_name='交换机'),
        ),
    ]
