# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0002_disk_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.SmallIntegerField(choices=[(0, 'VLAN'), (1, 'TRUNK'), (2, 'RIP'), (3, 'OSPF'), (4, 'IBGP'), (5, 'EBGP'), (6, 'BIND')], default=0, verbose_name='协议类型'),
        ),
    ]
