# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-26 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0002_auto_20190626_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_user', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户使用')),
                ('cpu_system', models.CharField(blank=True, max_length=64, null=True, verbose_name='系统使用')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='内存使用率')),
                ('disk', models.CharField(blank=True, max_length=64, null=True, verbose_name='磁盘使用率')),
                ('network', models.CharField(blank=True, max_length=64, null=True, verbose_name='网络')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor', to='cmdbServer.Servers')),
            ],
            options={
                'verbose_name': '资源使用率',
                'verbose_name_plural': '资源使用率',
            },
        ),
    ]
