# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-12 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0002_auto_20190611_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servers',
            name='userinfo',
        ),
        migrations.AddField(
            model_name='servers',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='servers',
            name='user',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名'),
        ),
    ]
