# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 15:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0003_auto_20181124_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='position',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(42), django.core.validators.MinValueValidator(1)], verbose_name='机柜位置'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='vlan',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='cmdbServer.Protocol', verbose_name='管理VLAN'),
        ),
        migrations.AlterUniqueTogether(
            name='servers',
            unique_together=set([('cabint', 'position')]),
        ),
    ]
