# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-22 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0004_auto_20190722_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='conn_status',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='连接状态'),
        ),
    ]
