# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-26 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0005_servers_conn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='port',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='SSH端口号'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='SSH密码'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='user',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='SSH用户名'),
        ),
    ]
