# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0007_auto_20181124_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='user',
            field=models.CharField(max_length=32),
        ),
    ]
