# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0008_auto_20181124_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=16, null=True, verbose_name='编号')),
                ('model', models.SmallIntegerField(choices=[(0, 'Round-robin policy(平衡抡循环策略'), (1, 'Active-backup policy(主-备份策略)'), (2, 'XOR policy(平衡策略)'), (3, 'broadcast(广播策略)'), (4, 'Dynamic link aggregation(IEEE802.3ad 动态链接聚合)'), (5, 'Adaptive transmit load balancing(适配器传输负载均衡)'), (6, 'Adaptive load balancing(适配器适应性负载均衡)')], default=0, verbose_name='Bonding模式')),
                ('ipaddress1', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址1')),
                ('ipaddress2', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址2')),
                ('ipaddress3', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址3')),
                ('ipaddress4', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址4')),
                ('nic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonding', to='cmdbServer.Nic', verbose_name='网卡')),
            ],
            options={
                'verbose_name': 'Bonding',
                'verbose_name_plural': 'Bonding',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bonding',
            unique_together=set([('ipaddress1', 'ipaddress2', 'ipaddress3', 'ipaddress4')]),
        ),
    ]
