# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-06 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0008_auto_20190806_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='Users',
        ),
        migrations.AddField(
            model_name='tasks',
            name='users',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='用户'),
        ),
    ]
