# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0009_auto_20181126_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonding',
            name='number',
        ),
        migrations.AddField(
            model_name='bonding',
            name='device',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='设备'),
        ),
    ]
