# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0010_auto_20181126_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonding',
            name='nic',
        ),
        migrations.AddField(
            model_name='bonding',
            name='nic',
            field=models.ManyToManyField(blank=True, null=True, related_name='bonding', to='cmdbServer.Nic', verbose_name='网卡'),
        ),
    ]
