# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-12 14:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0010_auto_20190812_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
