# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-12 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0011_auto_20190812_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='result',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='执行结果'),
        ),
    ]
