# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0011_auto_20181126_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonding',
            name='nic',
            field=models.ManyToManyField(related_name='bonding', to='cmdbServer.Nic', verbose_name='网卡'),
        ),
    ]
