# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-13 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0012_auto_20190812_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=128, null=True, verbose_name='文件路径')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Job',
            },
        ),
    ]
