# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0015_auto_20190814_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
