# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-15 14:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbServer', '0017_auto_20190815_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='执行结果'),
        ),
    ]
